language: node_js

node_js:
  - 0.10
  - 0.12

before_install:
  - make configure

script:
  - make test
  - make coverage | ./node_modules/.bin/coveralls

branches:
  except:
    - docs
    - gh-pages
